import type { WorkspaceTask } from "@/lib/types";
import { SIM_ASSISTANT_LINES } from "@/lib/features/chat-streaming";
import { config } from "@/lib/config";

/**
 * Sidecar port. Sourced from the validated config object (which reads
 * NEXT_PUBLIC_SIM_PORT, defaulting to 4001) instead of an ad-hoc process.env
 * read. Override via the env var for non-default setups.
 */
export const SIM_PORT = config.simPort;

/** Commands cycled by the simulation when fabricating command messages. */
export const SIM_COMMANDS: string[] = [
  "Ran npm run lint",
  "Ran npm test",
  "Ran git diff --stat",
  "Ran tsc --noEmit",
  "Ran prettier --check .",
  "Ran node —check app.js",
  "Ran git status",
];

function pick<T>(arr: T[]): T {
  const v = arr[Math.floor(Math.random() * arr.length)];
  if (!v) throw new Error("pick: empty array");
  return v;
}

/**
 * Resolve the socket.io connection target + options.
 *
 * Two deployment shapes are supported:
 *
 * 1. Direct dev (no reverse proxy): the client connects straight to the
 *    sidecar at http://localhost:<SIM_PORT>, using path "/". This is the
 *    default and what `bun run dev` + `bun run sim` use.
 *
 * 2. Behind the Caddy proxy: set NEXT_PUBLIC_SIM_PROXY=1 so the client
 *    connects same-origin via "/?XTransformPort=<SIM_PORT>" (Caddy's
 *    @transform_port_query matcher routes it to the sidecar). This mirrors
 *    examples/websocket/frontend.tsx and is what the production Caddyfile
 *    expects.
 *
 * Both use path: "/" to match sim-server.ts (which intentionally uses "/"
 * rather than socket.io's default "/socket.io/").
 */
export function resolveSimTarget(): { url: string; path: string } {
  // Explicit full URL wins (e.g. NEXT_PUBLIC_SIM_URL=http://box:4001).
  const explicit = process.env.NEXT_PUBLIC_SIM_URL;
  if (explicit) return { url: explicit, path: "/" };

  const useProxy = process.env.NEXT_PUBLIC_SIM_PROXY === "1";
  if (useProxy) {
    // Same-origin; Caddy reads XTransformPort and proxies to the sidecar.
    return { url: `/?XTransformPort=${SIM_PORT}`, path: "/" };
  }
  // Default: direct to the sidecar (dev without Caddy).
  return { url: `http://localhost:${SIM_PORT}`, path: "/" };
}

/** Fabricate a plausible assistant plan message (used for streamed replies). */
export function randomAssistantPlan(task: WorkspaceTask): string {
  const lead = pick(SIM_ASSISTANT_LINES);
  const tail = pick([
    `Then I'll apply the change to ${task.branch} and show you the diff.`,
    `This keeps the change minimal and safe for ${task.goal.toLowerCase()}.`,
    `Let me know if you'd like me to take a different approach here.`,
    `I'll commit it once the checklist for this task is complete.`,
  ]);
  return `${lead} ${tail}`;
}

/** Fabricate a brand-new task (for the left-sidebar new-task animation). */
export function randomNewTask(now = Date.now()): WorkspaceTask {
  const titles = [
    "Add keyboard shortcut to toggle the AI focus overlay",
    "Refactor the board renderer to use a canvas backing store",
    "Improve win-detection perf for very large boards",
    "Add a dark-mode variant for the marketing hero",
    "Cache the docs search index in localStorage",
  ];
  const total = 3 + Math.floor(Math.random() * 3);
  return {
    id: `task-sim-${now}-${Math.floor(Math.random() * 1e4)}`,
    title: pick(titles),
    tags: ["simulated"],
    branch: `feat/sim-${Math.floor(Math.random() * 1000)}`,
    project: "simulation",
    goal: "Live-simulated task generated by the websocket sidecar",
    status: "active",
    model: pick(["GLM-5.2", "Claude Sonnet 4.6", "GPT-5.4"]),
    tokensUsed: 0,
    stepCount: 0,
    totalSteps: total,
    duration: "0m",
    createdAt: new Date(now).toISOString(),
    updatedAt: new Date(now).toISOString(),
  };
}
